# Site settings
title: Tejveer Singh's CV 
description: Teju's CV
favicon: /assets/img/avatar.JPG
baseurl: https://tskhurana.github.io/teju/
url: https://tskhurana.github.io/teju/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Tejveer Singh
  title: Grad Student at cal State Uni Long Beach
  address: Long Beach, USA
  email: tejveer.khurana#gmail.com
  link: https://tskhurana.github.io/
  weibo:
  github: tskhurana
  linkedin: tejveers
  twitter: _Tejveer_
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Infosys Ltd
      location: Pune, India
      title: Senior Systems Engineer
      started: 2014
      duration: (2014 - Present)
      description: Work Flow Tool (C# web application, SQL, PL/SQL): WFT is British Telecomâ€™s Pre-Billing & Payments application, interferes with the Billing system and generates the verified charges and corrected invoices for Openreach customers.\n Enquiry Management System (C# web application, SQL, PL/SQL): EMS organizes, tracks and eases the wide scale validation process for Queries/Disputes in a service area under Post Billing & Payments Platform for British Telecom. It helped replacing Jira for some team.\n Final Billing Tool (C# desktop application, SQL, PL/SQL): Automated tool to upload various types of files in the database on a single click and generate final billing files after applying business logics.\n Responsibilities: Gathering requirements from client. Leading development, testing & deployment activities. Building & Designing web applications along with SQL stored procedures. Delivering workflow automation using SQL Stored procedures and Scheduled Jobs. Maintaining massive scaled database. Giving live support to clients.\n Accomplishments: Automated Work Flow Tool to Final Billing Tool, resulted in 60% productivity increase. Built & delivered a robust Enquiry Management System reducing 50% of man power. Optimized SQL procedures to retrieve data. Build SQL procedure to generate 6 crucial reports in a single query. Independently carried out 2 major upgrades of EMS within timescales with no glitch.
  educationHistory:
    - education1:
      organization: California State University, Long Beach
      location: Long Beach, USA
      degree: Masters
      major: Computer Science
      started: 2017
      duration: (2017 - 2019)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Punjabi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: SQL
      percentage: 80%
    - skill2:
      name: C#
      percentage: 70%
    - skill3:
      name: ADO.NET
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
